<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Place lidar just above chassis -->
  <joint name="camera_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_link" />
    <origin xyz="${chassis_depth/2} 0 ${chassis_height + 0.060}" rpy="0 0 3.14159" />
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder box="0.010 0.03 0.03" />
      </geometry>
      <material name="white" />
    </visual>
  </link>

  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link" />
    <child link="camera_link_optical" />
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${pi/2}" />
  </joint>

  <link name="camera_link_optical" />

  <gazebo reference="camera_link">
    <material>Gazebo/White</material>
    <!-- <sensor>
      <name>camera</name>
      <type>camera</type>
      <update_rate>30</update_rate>
      <topic>camera/image_raw</topic>
      <always_on>1</always_on>
      <visualize>true</visualize>
      <camera>
        <horizontal>
          <resolution>640</resolution>
          <fov>1.047</fov>
        </horizontal>
        <vertical>
          <resolution>480</resolution>
          <fov>0.785</fov>
        </vertical>
      </camera>
    </sensor> -->
  </gazebo>

</robot>