<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Filename: depth_camera.xacro -->

  <!-- Define fallback properties - these will be overridden if already defined -->
  <xacro:property name="chassis_depth" value="0.368" />
  <xacro:property name="chassis_height" value="0.62" />

  <!-- Place depth camera at front of chassis -->
  <joint name="depth_camera_joint" type="fixed">
    <parent link="base_link" />
    <child link="depth_camera_link" />
    <origin xyz="${chassis_depth/2 - 0.012} 0 ${chassis_height + 0.060}" rpy="0 0 0" />
  </joint>

  <link name="depth_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.028 0.075 0.0175" /> <!-- 75mm x 28mm x 17.5mm -->
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.028 0.075 0.0175" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.05" /> <!-- Approximate mass in kg -->
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5" /> <!-- Simple inertia -->
    </inertial>
  </link>

  <joint name="depth_camera_optical_joint" type="fixed">
    <parent link="depth_camera_link" />
    <child link="depth_camera_link_optical" />
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
  </joint>

  <link name="depth_camera_link_optical" />

  <gazebo reference="depth_camera_link">
    <material>Gazebo/White</material>
    <sensor name="depth_camera" type="depth">
      <update_rate>10</update_rate>
      <always_on>1</always_on>
      <visualize>true</visualize>
      <topic>depth_camera</topic>
      <camera>
        <horizontal_fov>1.089</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R_FLOAT32</format> <!-- Depth format, not RGB -->
        </image>
        <clip>
          <near>0.05</near>
          <far>8.0</far>
        </clip>
        <depth_camera>
          <output>depths</output>
        </depth_camera>
      </camera>
    </sensor>
  </gazebo>

</robot>