<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Gazebo DiffDrive plugin configuration for LabRobot -->

    <!-- Define fallback properties - these will be overridden if already defined -->
    <xacro:property name="wheelbase_y" value="0.1605" /> <!-- chassis_width/2 -->
    <xacro:property name="wheel_radius" value="0.0325" /> <!-- wheel_diameter/2 -->

    <gazebo>
        <plugin name="gz::sim::systems::DiffDrive" filename="gz-sim-diff-drive-system">
            <left_joint>left_wheel_to_base_link</left_joint>
            <right_joint>right_wheel_to_base_link</right_joint>

            <wheel_separation>${2 * wheelbase_y}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

            <topic>/cmd_vel</topic>
            <odom_topic>/odom</odom_topic>
            <odom_publish>true</odom_publish>
            <frame_id>odom</frame_id>
            <child_frame_id>base_footprint</child_frame_id>
            <tf_topic>/tf</tf_topic>
            <update_rate>50</update_rate>
            <publish_tf>true</publish_tf>
            <publish_odom>true</publish_odom>
            
        </plugin>
    </gazebo>
</robot>