<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- filename: lidar.xacro -->

    <xacro:property name="lidar_sensor_diameter" value="0.051" />
    <xacro:property name="lidar_sensor_height" value="0.045" />

    <!-- Place lidar just above chassis -->
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_frame" />
        <origin xyz="${chassis_depth/2 - (lidar_sensor_diameter)} 0 ${chassis_height + 0.060}" rpy="0 0 3.14" />
    </joint>

    <link name="lidar_frame">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 3.14" />
            <geometry>
                <cylinder radius="${lidar_sensor_diameter / 2}" length="0.01" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 3.14" />
            <geometry>
                <cylinder radius="${lidar_sensor_diameter / 2}" length="0.01" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
        </inertial>
    </link>

    <gazebo reference="lidar_frame">
        <material>Gazebo/White</material>
        <sensor name="laser" type="gpu_lidar">
        <pose>0 0 0 0 0 0</pose>
        <update_rate>10</update_rate>
        <topic>scan</topic>
        <always_on>1</always_on>
        <visualize>true</visualize>
        <lidar>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1</resolution>
              <min_angle>-3.14</min_angle>
              <max_angle>3.14</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.3</min>
            <max>12.0</max>
            <resolution>0.01</resolution>
          </range>
        </lidar>
      </sensor>
    </gazebo>

</robot>